version: '3'
services:
  apiserver:
    build:
      context: ./
      dockerfile: ./Dockerfile-apiserver
    ports:
      - "8080:8080"
    environment:
      - SLOW_STORAGE_TYPE=local
      - LOCAL_STORAGE_BASE_PATH=/tmp/einvoice
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=a
      - DB_NAME=einvoice
  einvoice-web-app:
    build:
      context: ./
      dockerfile: Dockerfile-einvoice-web-app
    ports:
      - "8081:8081"
    environment:
      - API_SERVER_URL=http://localhost:8080