---
location: us-west1
sql_instance:
  backend_type: SECOND_GEN
  database_version: POSTGRES_12
  tier: db-g1-small
  db_user: einvoice
  db_password: 12345
  db_name: einvoice
docker_password: " {{ lookup('file', '/home/filip/mfsr/webserver1-283520-386230d8738c.json')}}"