---
- service: name=docker state=started

- name: Build authproxy and push it to a private repo
  docker_image:
    build:
      path: ../
      dockerfile: Dockerfile-authproxy
    name: 'gcr.io/{{ project_id }}/authproxy'
    tag: latest
    push: yes
    force: yes
    source: build
    state: present

- name: Deploy cloud run authproxy
  command: gcloud run deploy authproxy --project '{{ project_id }}' --image gcr.io/{{ project_id }}/authproxy:latest --platform managed --region '{{ location }}' --allow-unauthenticated --vpc-connector redis-connector --set-env-vars APISERVER_URL='{{ apiserver_url }}' --set-env-vars REDIS_URL='{{redis.host}}:{{redis.port}}' --set-env-vars API_TOKEN_PRIVATE="MIIEpAIBAAKCAQEA7FvSoKZ707SVMO6dLnnrrI7xo1ORAcKMbS4vd6RSuZTz1FHW QL5T2ZpcHkdc2kY/N9l7ZA/buCMq7HkH5M+U9fHzLZYUygf8LXUQOQBgni90hPY3 EirfUU0tE256Qd9kD1r5AzWyKG0Jh2OxT7O8vgcMZbX8xJ7c9cJPcreiUo7nqry7 sbBE/5F/AEUcIDBMbG92P+6DZAYr1+kxztQgy0YES6bHNT+ARqgbUjBHmQXxBxjy r2QgaDG+Rw/PRWEo0gSVgtjDUJI61+E2/bS0WdVdn5gy1s2W0bx8MW+wIb1J0Ina CwJyS48OlUwiOZ+LbrT+cEvsHOx4l0bAt60HvQIDAQABAoIBAA1gYPpAkc94b90W FAU2VzUr3dcNeq5r0UC4lW0i+p+QI4CHpSWC4AH3r3DzPvkHcrp5b3dJQnkYXGyH qP+1E8wbhlS1IrYQX6A++M0RDWbGbsS7noBDtuHGCWAJJ5gkyWfpESCyYEPTb++e n8FP/cWPZo83DngeOYkbFx358JDVc8PJQ9n6GVL4M9aS/EAbw2fkXgGWXG0YD/A3 eY1WRRrnUMYK5xWnfBTZqOXIe1MBLZ2gMLvWo633tl/jhyksvyKbOBY9eiv048sr /jE8O/AdN763Hy2KE6XAeT0t7vRtbA5nmei77CXLJ3yvXCpUwsKTArdAuefOBxaw cO/x4+0CgYEA+wVYfB5lAdTaMeZROlgpQq7kP0K3D8oYVej28xm7jC44GNG4Q6Ex jJQH2gI1c3yNSO6q0JG9mDzo62NXf65HS8+4v32+VUs7Afx75KTFtyhRyuYViC6C teAZLzaX7M6NoD7knpVo43V2NQu0PpyDsGwOV5aQJzHQp+f1BcC2iAsCgYEA8QwG MoN91Y5qWw8g5V0ue5SPkfZbr9NSML8EWDBzCXRfLiBLnWxCSdAvWosshDhSPOs8 EWkiUgO1TTkJef1loJdJ7LI9Hnp3MjoJ6Y6r9RgIy0H5h1eFHqkoPIH5gVDQPdaw vLaPfS+8IoELlEKyLXe6GIKqx29/AZJLMvdR5FcCgYAQOJE2PBSU4LdU4ChBl+7a o0iWme4QdCPMcWh73x7SeS4g1HSO0jzMc8hqGxhvJQ5QNzQMlE5nJxB6HYpK8u0i hgLPRQXmpxziDPnIlak9I7rdXK7phO/nZtrZxTJeGB7oywelA8yqXi3MUbxNC3or DWCD4nPgRITSRNf9ji19bwKBgQDBWLu/2OkeW1XEJKZmVA/s4IUot0tkBUVwBEgf 1PzxIH8YKJ9+bk/dlTfmkKvsgqC0bJuJ+6Kj1oWeo5mOWEskPTX2viF4SRNDHnrE 9MPJnLWxFAJrJTCKH3U+06Kmr4PZllO9i1IdQCTQKGJ5UeZJwjdrYaRKxIxDXm0j PG5bkQKBgQCnZbMX2W8O0pPORN3jZWCXPOAgr+3lgKUSS7+htVRoQv3iDmsqea59 QQhQPdecH4fo1p0YVXK3Dgy/cfOpWN77MVm179sDVW1x1MmhevDffGT6jauX3giy Vxiwvd5XS3KADZE2qy2hdZIWIuVmW5BVzdk5xFDkmd+2XiMsIar0uA==" --set-env-vars OBO_TOKEN_PUBLIC="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyBMmycAXwvi2ERpSAJmj cq9Ngm0ckcso1a5lJI4QnqnF3TrWdPDL9tlJVnGqHhZUQ/SrvmuG6EV8S3ro+7ZO F5wu7O41dE+Tlf2Fy4jfKa06A7Yvt/L9Stp2ZeK6LQ1fq4QpmZ15NzUoDEYYTMUw y6P6oBZp3FNlPYXyCRAlFCOeWPqivSGEp2E6gLWqFoFovYJBAP+mDVKM9Qkb+IYc 3/2y+5d94VyTaLF/jy/NZPXu1GBIPLes5rjzRMwn9ZKx86azdeJ0POlAmavxsgbr Lf9H6LbcOOO90xP6j58j0c8RGLadIN+ur04wW3mb02Lbtok55dVmORfje6BtQV5T iwIDAQAB" --set-env-vars SLOVENSKO_SK_URL=https://upvs.dev.filipsladek.com

- name: Deploy cloud get service authproxy
  shell: gcloud run services describe authproxy --project '{{ project_id }}' --platform managed --region '{{ location }}' --format 'value(status.url)'
  register: authproxy_output

- name: Domain mapping authproxy
  command: gcloud beta run domain-mappings create --project '{{ project_id }}' --service authproxy --domain authproxy.dev.filipsladek.com --platform managed --region '{{ location }}'
  ignore_errors: yes

- name: Domain mapping authproxy
  command: gcloud beta run domain-mappings describe --project '{{ project_id }}' --domain authproxy.dev.filipsladek.com --platform managed --region '{{ location }}'
  register: authproxy_domain_mapping_output

- debug:
    msg: authproxy_domain_mapping_output={{ authproxy_domain_mapping_output }}

- set_fact: authproxy_url="{{ authproxy_output.stdout }}"

- debug:
    msg: authproxy_url={{ authproxy_url }}
