---
- service: name=docker state=started

- name: Build authproxy and push it to a private repo
  docker_image:
    build:
      path: ../
      dockerfile: Dockerfile-authproxy
    name: 'gcr.io/{{ project_id }}/authproxy'
    tag: latest
    push: yes
    force: yes
    source: build
    state: present

- name: Deploy cloud run authproxy
  command: gcloud run deploy authproxy --project '{{ project_id }}' --image gcr.io/{{ project_id }}/authproxy:latest --platform managed --region '{{ location }}' --allow-unauthenticated --set-env-vars APISERVER_URL='{{ apiserver_url }}' --set-env-vars REDIS_URL='{{redis.host}}:{{redis.port}}' --vpc-connector redis-connector

- name: Deploy cloud get service authproxy
  shell: gcloud run services describe authproxy --project '{{ project_id }}' --platform managed --region '{{ location }}' | egrep -A 1 Traffic | egrep -B 1 LATEST | egrep -o 'https?://[^ ]+'
  register: authproxy_output

- set_fact: authproxy_url="{{ authproxy_output.stdout }}"

- debug:
    msg: authproxy_url={{ authproxy_url }}
