---
- name: Create authproxy sql instance
  gcp_sql_instance:
    name: '{{ authproxy_sql.instance_name }}'
    backend_type: '{{ authproxy_sql.backend_type }}'
    database_version: '{{ authproxy_sql.database_version }}'
    settings:
      tier: '{{ authproxy_sql.tier }}'
    region: '{{ location }}'
    project: '{{ project_id }}'
    state: present
  register: sql_authproxy_instance_res_tmp

- name: Enable private ip
  command: >
    gcloud beta sql instances patch {{sql_authproxy_instance_res_tmp.name}}
      --project={{ project_id }}
      --network=default
      --no-assign-ip

- name: Get sql instance info
  gcp_sql_instance:
    name: '{{ authproxy_sql.instance_name }}'
    backend_type: '{{ authproxy_sql.backend_type }}'
    database_version: '{{ authproxy_sql.database_version }}'
    settings:
      tier: '{{ authproxy_sql.tier }}'
    region: '{{ location }}'
    project: '{{ project_id }}'
    state: present
  register: sql_authproxy_instance_res

- name: Create database
  ignore_errors: yes
  gcp_sql_database:
    name: '{{ authproxy_sql.db_name }}'
    charset: utf8
    instance: "{{ sql_authproxy_instance_res.name }}"
    project: '{{ project_id }}'
    state: present

- name: Create a user
  ignore_errors: yes
  gcp_sql_user:
    name: '{{ authproxy_sql.db_user }}'
    host: '{{ sql_authproxy_instance_res.ipAddresses[0].ipAddress }}'
    password: '{{ authproxy_sql.db_password }}'
    instance: "{{ sql_authproxy_instance_res }}"
    project: '{{ project_id }}'
    state: present

- name: Enable vpc connectors
  command: >
    gcloud services enable vpcaccess.googleapis.com
      --project {{project_id}}
