---
- name: Build web-app and push it to a private repo
  docker_image:
    build:
      path: ../
      dockerfile: Dockerfile-einvoice-web-app
    name: 'gcr.io/{{ project_id }}/web-app'
    tag: latest
    push: yes
    force: yes
    source: build
    state: present

- name: Deploy cloud run
  command: gcloud run deploy web-app --image gcr.io/{{ project_id }}/web-app:latest --platform managed --region {{ location }} --allow-unauthenticated --set-env-vars API_SERVER_URL='{{ authproxy_url }}'

- name: Deploy cloud get service
  shell: gcloud run services describe web-app --platform managed --region '{{ location }}' | egrep -A 1 Traffic | egrep -B 1 LATEST | egrep -o 'https?://[^ ]+'
  register: web_app_shell_output

- set_fact: web_app_url="{{ web_app_shell_output.stdout }}"

- debug:
    msg: web_app_url={{ web_app_url }}
