---
- name: Build web-app and push it to a private repo
  docker_image:
    build:
      path: ../
      dockerfile: Dockerfile-einvoice-web-app
    name: 'gcr.io/{{ project_id }}/web-app'
    tag: latest
    push: yes
    force: yes
    source: build
    state: present

- name: Deploy cloud run
  command: gcloud run deploy web-app --image gcr.io/{{ project_id }}/web-app:latest --platform managed --region europe-west1 --allow-unauthenticated --set-env-vars API_SERVER_URL='http://{{ authproxy_loadbalancer_ip }}'

- name: Deploy cloud get service
  shell: gcloud run services list --platform managed --filter=app2 | grep http | egrep -o 'https?://[^ ]+'
  register: shell_output

- set_fact: url="{{ shell_output.stdout }}"

- debug:
    msg: url={{ url }}
