---
- name: Build web-app and push it to a private repo
  docker_image:
    build:
      path: ../
      dockerfile: Dockerfile-web-app
    name: 'gcr.io/{{ project_id }}/web-app'
    tag: latest
    push: yes
    force: yes
    source: build
    state: present

- name: Deploy cloud run web-app
  command: >
    gcloud run deploy web-app
      --project '{{ project_id }}'
      --image gcr.io/{{ project_id }}/web-app:latest
      --platform managed
      --region {{ location }}
      --allow-unauthenticated
      --set-env-vars AUTH_SERVER_URL='{{ authproxy_url }}'
      --set-env-vars WEBSERVER_ENV=prod

- name: Deploy cloud get service web-app
  command: >
    gcloud run services describe web-app
      --project '{{ project_id }}'
      --platform managed
      --region '{{ location }}'
      --format 'value(status.url)'
  register: web_app_shell_output

- set_fact: web_app_url="{{ web_app_shell_output.stdout }}"

- debug:
    msg: web_app_url={{ web_app_url }}
