# ansible-playbook apiserver.yaml
---
- hosts: localhost
  tasks:
    - service: name=docker state=started
    - name: Docker Login
      docker_login:
        registry: gcr.io/webserver1-283520/apiserver
        username: _json_key
        debug: true
        password: " {{ lookup('file', '/home/filip/mfsr/webserver1-283520-386230d8738c.json')}}"
    - name: Build an image and push it to a private repo
      docker_image:
        build:
          path: ../
          dockerfile: Dockerfile-apiserver
        name: gcr.io/webserver1-283520/apiserver
        tag: latest
        push: yes
        source: build
        state: present
    - name: Create a Deployment by reading the definition from a local file
      k8s:
        state: present
        name: develop
        api_version: v1
        src: kubernetes/apiserver.yaml
