# export GCP_AUTH_KIND=serviceaccount
# export GCP_SERVICE_ACCOUNT_FILE=/home/filip/webserver1-283520-386230d8738c.json
# export GCP_SCOPES=https://www.googleapis.com/auth/compute,https://www.googleapis.com/auth/cloud-platform
# ansible-playbook cluster.yaml
---
- hosts: localhost
  vars:
    location: us-west1
    project: webserver1-283520
  tasks:
    - name: create a cluster
      gcp_container_cluster:
        name: my-cluster1
        initial_node_count: 2
        master_auth:
          username: cluster_admin
          password: my-secret-password
        location: '{{ location }}'
        project: webserver1-283520
#        auth_kind: serviceaccount
#        service_account_file: "/home/filip/webserver1-283520-386230d8738c.json"
        state: present
      register: cluster
    - name: create a node pool
      gcp_container_node_pool:
        name: my-pool
        initial_node_count: 1
        cluster: "{{ cluster }}"
        location: '{{ location }}'
        project: '{{ project }}'
        config:
          oauth_scopes: ['https://www.googleapis.com/auth/devstorage.read_only']
          machine_type: n1-standard-4
          disk_size_gb: 500
        state: present
        autoscaling:
          enabled: no
