# export GCP_AUTH_KIND=serviceaccount
# export GCP_SERVICE_ACCOUNT_FILE=/home/filip/webserver1-283520-386230d8738c.json
# export GCP_SCOPES=https://www.googleapis.com/auth/compute,https://www.googleapis.com/auth/cloud-platform
# ansible-playbook db.yaml
---
- hosts: localhost
  vars:
    ### Cloud_SQL instance specifications
    # backend_type: FIRST_GEN / SECOND_GEN / EXTERNAL
    # database_version: MYSQL_5_5 / MYSQL_5_6 / MYSQL_587 / POSTGRESQL_9_6
    # tier: db-g1-smal / db-pg-g1-small / custom-2-2048
    sql_instance:
      name: webserverdb1
      backend_type: SECOND_GEN
      database_version: POSTGRES_12
      region: us-west1
      tier: db-g1-small
    project_id: webserver1-283520
  tasks:
    - name: Create GCP CloudSQL instance
      gcp_sql_instance:
        name: '{{ sql_instance.name }}'
        backend_type: '{{ sql_instance.backend_type }}'
        database_version: '{{ sql_instance.database_version }}'
        settings:
          tier: '{{ sql_instance.tier }}'
        region: '{{ sql_instance.region }}'
        project: '{{ project_id }}'
        state: present