# export GCP_AUTH_KIND=serviceaccount
# export GCP_SERVICE_ACCOUNT_FILE=/home/filip/webserver1-283520-386230d8738c.json
# export GCP_SCOPES=https://www.googleapis.com/auth/compute,https://www.googleapis.com/auth/cloud-platform
# ansible-playbook db.yaml
---
- hosts: localhost
  vars:
    storage_instance:
      name: webserverstorage1
    project_id: webserver1-283520
  tasks:
    - name: create a bucket
      gcp_storage_bucket:
        name: '{{ storage_instance.name }}'
        project: '{{ project_id }}'
        state: present